title: MockMind
theme: jekyll-theme-minimal

nav:
  - title: "Intro"
    url: /intro/
  - title: "Manifest"
    url: /manifest/
  - title: "Ethics"
    url: /ethics/
  - title: "Legal"
    url: /legal/
  - title: "Agents"
    url: /agents/
  - title: "Engine"
    url: /engine/
  - title: "Map"
    url: /map/
  - title: "Contribute"
    url: /contribute/
  - title: "Containment"
    url: /containment/
  - title: "Roadmap"
    url: /roadmap/
  - title: "Identity"
    url: /identity/
  - title: "Philosophy"
    url: /philosophy/
  - title: "FAQ"
    url: /faq/
  - title: "Press"
    url: /press/
  - title: "Educators"
    url: /educators/
  - title: "License"
    url: /license/
  - title: "Terms"
    url: /terms/
  - title: "Credits"
    url: /credits/
  - title: "History"
    url: /history/
  - title: "Glossary"
    url: /glossary/
  - title: "Auth"
    url: /auth/
