title: MockMind
theme: jekyll-theme-minimal

nav:
  - title: "Home"
    url: /
  - title: "Manifest"
    url: /manifest/
  - title: "Ethics"
    url: /ethics/
  - title: "Legal"
    url: /legal/
  - title: "Agents"
    url: /agents/
  - title: "Engine"
    url: /engine/
  - title: "Map"
    url: /map/
  - title: "Contribute"
    url: /contribute/
  - title: "Containment"
    url: /containment/
  - title: "Roadmap"
    url: /roadmap/
  - title: "Identity"
    url: /identity/
  - title: "Philosophy"
    url: /philosophy/
